name: Build and Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release tag(e.g., 1.2.3) without starting 'v'"
        required: true
        default: "continuous"
        type: string
      prerelease:
        description: "Set as prerelease"
        required: true
        default: true
        type: boolean
      publish:
        description: "Publish release"
        required: true
        default: true
        type: boolean
#  push:
#    branches: [main]
#    paths:
#      - 'src/**'
#      - 'HeadsetControl-GUI.pro'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            os_name: windows
            architecture: x64
            shell: pwsh
            headsetcontrol: "https://github.com/Sapd/HeadsetControl/releases/latest/download/headsetcontrol-windows-x86_64.zip"
            headsetcontrol_continuous: "https://github.com/Sapd/HeadsetControl/releases/download/continuous/headsetcontrol-windows-x86_64.zip"
            dependencies: |
              choco install zip
              Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
            build: |
              mkdir build
              cd build
              qmake ../HeadsetControl-GUI.pro CONFIG+=release
              nmake
          - os: ubuntu-latest
            os_name: linux
            architecture: x64
            shell: bash
            headsetcontrol: "https://github.com/Sapd/HeadsetControl/releases/latest/download/headsetcontrol-linux-x86_64.zip"
            headsetcontrol_continuous: "https://github.com/Sapd/HeadsetControl/releases/download/continuous/headsetcontrol-linux-x86_64.zip"
            dependencies: |
              sudo apt-get update
              sudo apt-get install -y zip
            build: |
              mkdir build
              cd build
              qmake ../HeadsetControl-GUI.pro CONFIG+=release
              make -j$(nproc)
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          add-tools-to-path: true
          cache: true
          host: ${{ matrix.os_name }}

      - name: Install dependencies
        run: ${{ matrix.dependencies }}

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: matrix.os_name == 'windows'
        with:
          arch: ${{ matrix.architecture }}

      - name: Build
        run: ${{ matrix.build }}

      - name: Deploy Qt Windows
        if: matrix.os_name == 'windows'
        run: |
          Get-ChildItem -Path build/ -Include *.cpp, *.h, *.obj, *.res, *.qrc, *.qm -Recurse | Remove-Item -Force
          Invoke-WebRequest -Uri ${{ inputs.prerelease && matrix.headsetcontrol_continuous || matrix.headsetcontrol }} -OutFile headsetcontrol-windows.zip
          Expand-Archive -Path headsetcontrol-windows.zip -DestinationPath build/release/
          windeployqt6 --exclude-plugins qsvgicon,qsvg,qico,qjpeg,qgif,qnetworklistmanager,qtuiotouchplugin --no-opengl-sw --no-system-dxc-compiler --no-compiler-runtime --no-translations --no-system-d3d-compiler build/release/HeadsetControl-GUI.exe
          
      - name: Deploy Qt
        if: matrix.os_name == 'linux'
        run: |
          curl -L ${{ matrix.headsetcontrol_continuous }} -o headsetcontrol-linux-x86_64.zip
          mkdir -p build/release/
          cp build/HeadsetControl-GUI build/release/
          unzip headsetcontrol-linux-x86_64.zip -d build/release/

      - name: zip binaries folder
        run: |
          cd build/release/
          zip -r ../../HeadsetControl-GUI_${{ matrix.os_name }}_${{ matrix.architecture }}.zip .
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HeadsetControl-GUI_${{ matrix.os_name }}_${{ matrix.architecture }}
          path: HeadsetControl-GUI_${{ matrix.os_name }}_${{ matrix.architecture }}.zip

  create-release:
    if: ${{ inputs.publish }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            merge-multiple: true
        - name: Deploy continuous
          uses: crowbarmaster/GH-Automatic-Releases@latest
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: ${{ inputs.version }}
            prerelease: ${{ inputs.prerelease }}
            title: Release ${{ inputs.version }}
            files: |
              HeadsetControl-GUI_*
            body: |
              ## Contributor
              @nicola02nb Mantainer
  
              ## Credits
              @Sapd for [HeadsetControl](https://github.com/Sapd/HeadsetControl)

  winget-release:
    if: ${{ inputs.publish && !(startsWith(github.ref, 'refs/tags/continuous') || inputs.prerelease) }}
    needs: [create-release]
    runs-on: ubuntu-latest
    steps:
    - name: Submit package to Windows Package Manager Community Repository
      uses: michidk/winget-updater@v1
      with:
        komac-token: ${{ secrets.WINGET_DEPLOY_TOKEN }}
        identifier: "LeoKlaus.HeadsetControl-GUI"
        repo: "HeadsetControl-GUI.HeadsetControl-GUI"
        url: "https://github.com/HeadsetControl-GUI/HeadsetControl-GUI/releases/download/{VERSION}/HeadsetControl-GUI_windows_x64.zip"